//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ikon.IKCMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceIKCMS_Components {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceIKCMS_Components() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IKCMS_Components.Resources.ResourceIKCMS_Components", typeof(ResourceIKCMS_Components).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenziali per il reset non valide o scadute..
        /// </summary>
        public static string Auth_ChangePassword_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth_ChangePassword_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operazione non consentita..
        /// </summary>
        public static string Auth_ChangePassword_InvalidOperation {
            get {
                return ResourceManager.GetString("Auth_ChangePassword_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La password attuale specificata non è valida..
        /// </summary>
        public static string Auth_ChangePassword_InvalidPassword1 {
            get {
                return ResourceManager.GetString("Auth_ChangePassword_InvalidPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica delle password fallita..
        /// </summary>
        public static string Auth_ChangePassword_InvalidPassword2 {
            get {
                return ResourceManager.GetString("Auth_ChangePassword_InvalidPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifica delle password fallita..
        /// </summary>
        public static string Auth_ChangePassword_InvalidPassword3 {
            get {
                return ResourceManager.GetString("Auth_ChangePassword_InvalidPassword3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica delle password fallita..
        /// </summary>
        public static string Auth_ChangePassword_InvalidPassword4 {
            get {
                return ResourceManager.GetString("Auth_ChangePassword_InvalidPassword4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifica delle password fallita..
        /// </summary>
        public static string Auth_ChangePassword_InvalidPassword5 {
            get {
                return ResourceManager.GetString("Auth_ChangePassword_InvalidPassword5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName o E-mail non disponibile, non è possibile gestire la password..
        /// </summary>
        public static string Auth_ChangePassword_InvalidUsername1 {
            get {
                return ResourceManager.GetString("Auth_ChangePassword_InvalidUsername1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName o E-mail {0} non valide..
        /// </summary>
        public static string Auth_ChangePassword_InvalidUsername2 {
            get {
                return ResourceManager.GetString("Auth_ChangePassword_InvalidUsername2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è consentito modificare gli account di root..
        /// </summary>
        public static string Auth_ChangePassword_NoRoot {
            get {
                return ResourceManager.GetString("Auth_ChangePassword_NoRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password modificata con successo..
        /// </summary>
        public static string Auth_ChangePassword_PasswordOK1 {
            get {
                return ResourceManager.GetString("Auth_ChangePassword_PasswordOK1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password modificata con successo..
        /// </summary>
        public static string Auth_ChangePassword_PasswordOK2 {
            get {
                return ResourceManager.GetString("Auth_ChangePassword_PasswordOK2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;account è stato disabilitato..
        /// </summary>
        public static string Auth_Login_AccountDisabled1 {
            get {
                return ResourceManager.GetString("Auth_Login_AccountDisabled1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;account è stato disabilitato per motivi di sicurezza (es. troppi tentativi di accesso con password errate)..
        /// </summary>
        public static string Auth_Login_AccountDisabled2 {
            get {
                return ResourceManager.GetString("Auth_Login_AccountDisabled2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le credenziali fornite non sono valide..
        /// </summary>
        public static string Auth_Login_CredentialInvalid {
            get {
                return ResourceManager.GetString("Auth_Login_CredentialInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richiesta non valida..
        /// </summary>
        public static string Auth_Login_InvalidRequest {
            get {
                return ResourceManager.GetString("Auth_Login_InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le istruzioni per rigenerare la password sono state inviate tramite E-mail..
        /// </summary>
        public static string Auth_Login_PasswordReset1 {
            get {
                return ResourceManager.GetString("Auth_Login_PasswordReset1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solamente gli utenti autentificati possono cambiare la propria password..
        /// </summary>
        public static string Auth_Login_PasswordReset2 {
            get {
                return ResourceManager.GetString("Auth_Login_PasswordReset2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci il tuo username o l&apos;E-mail utilizzata durante la registrazione.&lt;br/&gt;Riceverai una E-mail con le istruzioni per reimpostare una nuova password..
        /// </summary>
        public static string Auth_Login_UsernameHelp {
            get {
                return ResourceManager.GetString("Auth_Login_UsernameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username o E-mail non valide..
        /// </summary>
        public static string Auth_Login_UsernameInvalid {
            get {
                return ResourceManager.GetString("Auth_Login_UsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utenza non è stata ancora confermata..
        /// </summary>
        public static string Auth_Login_UserUnconfirmed {
            get {
                return ResourceManager.GetString("Auth_Login_UserUnconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenziali non sufficienti per l&apos;operazione richiesta..
        /// </summary>
        public static string Auth_Register_ExceptionInvalidCredentials {
            get {
                return ResourceManager.GetString("Auth_Register_ExceptionInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operazione non valida oppure utente non esistente nel database..
        /// </summary>
        public static string Auth_Register_ExceptionInvalidOperation {
            get {
                return ResourceManager.GetString("Auth_Register_ExceptionInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrello abbandonato.
        /// </summary>
        public static string CartStatus_abandoned {
            get {
                return ResourceManager.GetString("CartStatus_abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout ordine.
        /// </summary>
        public static string CartStatus_checkout {
            get {
                return ResourceManager.GetString("CartStatus_checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout ordine: conferma dell&apos;ordine.
        /// </summary>
        public static string CartStatus_checkout_Confirm {
            get {
                return ResourceManager.GetString("CartStatus_checkout_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout ordine: scelta della modalità di pagamento.
        /// </summary>
        public static string CartStatus_checkout_PaymentMode {
            get {
                return ResourceManager.GetString("CartStatus_checkout_PaymentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nell&apos;ordine.
        /// </summary>
        public static string CartStatus_error {
            get {
                return ResourceManager.GetString("CartStatus_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore di pagamento in contrassegno.
        /// </summary>
        public static string CartStatus_error_Bonifico {
            get {
                return ResourceManager.GetString("CartStatus_error_Bonifico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore di pagamento in contrassegno.
        /// </summary>
        public static string CartStatus_error_Conrassegno {
            get {
                return ResourceManager.GetString("CartStatus_error_Conrassegno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore di pagamento con PayPal.
        /// </summary>
        public static string CartStatus_error_PayPal {
            get {
                return ResourceManager.GetString("CartStatus_error_PayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore di spedizione dell&apos;ordine.
        /// </summary>
        public static string CartStatus_error_Shipping {
            get {
                return ResourceManager.GetString("CartStatus_error_Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordine confermato.
        /// </summary>
        public static string CartStatus_finalized {
            get {
                return ResourceManager.GetString("CartStatus_finalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordine completato.
        /// </summary>
        public static string CartStatus_finalized_Done {
            get {
                return ResourceManager.GetString("CartStatus_finalized_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordine pagato.
        /// </summary>
        public static string CartStatus_finalized_Paid {
            get {
                return ResourceManager.GetString("CartStatus_finalized_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordine spedito.
        /// </summary>
        public static string CartStatus_finalized_Shipping {
            get {
                return ResourceManager.GetString("CartStatus_finalized_Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordine in contrassegno e spedito.
        /// </summary>
        public static string CartStatus_finalized_ShippingContrassegno {
            get {
                return ResourceManager.GetString("CartStatus_finalized_ShippingContrassegno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordine con bonifico in attesa di conferma pagamento.
        /// </summary>
        public static string CartStatus_finalized_WaitingBonifico {
            get {
                return ResourceManager.GetString("CartStatus_finalized_WaitingBonifico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordine in contrassegno in attesa di essere spedito.
        /// </summary>
        public static string CartStatus_finalized_WaitingContrassegno {
            get {
                return ResourceManager.GetString("CartStatus_finalized_WaitingContrassegno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordine con PayPal in attesa di conferma pagamento.
        /// </summary>
        public static string CartStatus_finalized_WaitingPayPal {
            get {
                return ResourceManager.GetString("CartStatus_finalized_WaitingPayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordine annullato.
        /// </summary>
        public static string CartStatus_nulled {
            get {
                return ResourceManager.GetString("CartStatus_nulled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordine annullato dallo shop.
        /// </summary>
        public static string CartStatus_nulled_ByShop {
            get {
                return ResourceManager.GetString("CartStatus_nulled_ByShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordine annullato su richiesta dell&apos;utente.
        /// </summary>
        public static string CartStatus_nulled_ByUser {
            get {
                return ResourceManager.GetString("CartStatus_nulled_ByUser", resourceCulture);
            }
        }
    }
}
