//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKGD_ResourceType_Library.IKGD_Indexer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.ikon.it/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IKGD_LuceneHit", Namespace="http://www.ikon.it/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IKGD_ResourceType_Library.IKGD_Indexer.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<IKGD_ResourceType_Library.IKGD_Indexer.IKGD_LuceneHit>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IKGD_ResourceType_Library.IKGD_Indexer.Document))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IKGD_ResourceType_Library.IKGD_Indexer.Object))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<IKGD_ResourceType_Library.IKGD_Indexer.ResourceData>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IKGD_ResourceType_Library.IKGD_Indexer.ResourceData))]
    public partial class IKGD_LuceneHit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IKGD_ResourceType_Library.IKGD_Indexer.Document docField;
        
        private float scoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guidField;
        
        private int rNodeField;
        
        private int vDataField;
        
        private System.Nullable<int> sNodeField;
        
        private System.Nullable<int> iNodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string areaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string manager_typeField;
        
        private bool flag_publishedField;
        
        private bool flag_currentField;
        
        private bool flag_unstructuredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string languageField;
        
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<IKGD_ResourceType_Library.IKGD_Indexer.ResourceData> resourceDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object pathsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public IKGD_ResourceType_Library.IKGD_Indexer.Document doc {
            get {
                return this.docField;
            }
            set {
                if ((object.ReferenceEquals(this.docField, value) != true)) {
                    this.docField = value;
                    this.RaisePropertyChanged("doc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float score {
            get {
                return this.scoreField;
            }
            set {
                if ((this.scoreField.Equals(value) != true)) {
                    this.scoreField = value;
                    this.RaisePropertyChanged("score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                if ((object.ReferenceEquals(this.guidField, value) != true)) {
                    this.guidField = value;
                    this.RaisePropertyChanged("guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int rNode {
            get {
                return this.rNodeField;
            }
            set {
                if ((this.rNodeField.Equals(value) != true)) {
                    this.rNodeField = value;
                    this.RaisePropertyChanged("rNode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int vData {
            get {
                return this.vDataField;
            }
            set {
                if ((this.vDataField.Equals(value) != true)) {
                    this.vDataField = value;
                    this.RaisePropertyChanged("vData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> sNode {
            get {
                return this.sNodeField;
            }
            set {
                if ((this.sNodeField.Equals(value) != true)) {
                    this.sNodeField = value;
                    this.RaisePropertyChanged("sNode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> iNode {
            get {
                return this.iNodeField;
            }
            set {
                if ((this.iNodeField.Equals(value) != true)) {
                    this.iNodeField = value;
                    this.RaisePropertyChanged("iNode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string area {
            get {
                return this.areaField;
            }
            set {
                if ((object.ReferenceEquals(this.areaField, value) != true)) {
                    this.areaField = value;
                    this.RaisePropertyChanged("area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string manager_type {
            get {
                return this.manager_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.manager_typeField, value) != true)) {
                    this.manager_typeField = value;
                    this.RaisePropertyChanged("manager_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool flag_published {
            get {
                return this.flag_publishedField;
            }
            set {
                if ((this.flag_publishedField.Equals(value) != true)) {
                    this.flag_publishedField = value;
                    this.RaisePropertyChanged("flag_published");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public bool flag_current {
            get {
                return this.flag_currentField;
            }
            set {
                if ((this.flag_currentField.Equals(value) != true)) {
                    this.flag_currentField = value;
                    this.RaisePropertyChanged("flag_current");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool flag_unstructured {
            get {
                return this.flag_unstructuredField;
            }
            set {
                if ((this.flag_unstructuredField.Equals(value) != true)) {
                    this.flag_unstructuredField = value;
                    this.RaisePropertyChanged("flag_unstructured");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                if ((object.ReferenceEquals(this.languageField, value) != true)) {
                    this.languageField = value;
                    this.RaisePropertyChanged("language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public System.Collections.Generic.List<IKGD_ResourceType_Library.IKGD_Indexer.ResourceData> resourceData {
            get {
                return this.resourceDataField;
            }
            set {
                if ((object.ReferenceEquals(this.resourceDataField, value) != true)) {
                    this.resourceDataField = value;
                    this.RaisePropertyChanged("resourceData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public object paths {
            get {
                return this.pathsField;
            }
            set {
                if ((object.ReferenceEquals(this.pathsField, value) != true)) {
                    this.pathsField = value;
                    this.RaisePropertyChanged("paths");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://www.ikon.it/")]
    [System.SerializableAttribute()]
    public partial class Document : IKGD_ResourceType_Library.IKGD_Indexer.Object {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Object", Namespace="http://www.ikon.it/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IKGD_ResourceType_Library.IKGD_Indexer.Document))]
    public partial class Object : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceData", Namespace="http://www.ikon.it/")]
    [System.SerializableAttribute()]
    public partial class ResourceData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pathField;
        
        private int sNodeResourceField;
        
        private int sNodeFolderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string path {
            get {
                return this.pathField;
            }
            set {
                if ((object.ReferenceEquals(this.pathField, value) != true)) {
                    this.pathField = value;
                    this.RaisePropertyChanged("path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int sNodeResource {
            get {
                return this.sNodeResourceField;
            }
            set {
                if ((this.sNodeResourceField.Equals(value) != true)) {
                    this.sNodeResourceField = value;
                    this.RaisePropertyChanged("sNodeResource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int sNodeFolder {
            get {
                return this.sNodeFolderField;
            }
            set {
                if ((this.sNodeFolderField.Equals(value) != true)) {
                    this.sNodeFolderField = value;
                    this.RaisePropertyChanged("sNodeFolder");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ikon.it/", ConfigurationName="IKGD_Indexer.IndexerSoap")]
    public interface IndexerSoap {
        
        // CODEGEN: Generating message contract since element name IKGD_IndexRebuildResult from namespace http://www.ikon.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ikon.it/IKGD_IndexRebuild", ReplyAction="*")]
        IKGD_ResourceType_Library.IKGD_Indexer.IKGD_IndexRebuildResponse IKGD_IndexRebuild(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_IndexRebuildRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ikon.it/IKGD_IndexUpdate", ReplyAction="*")]
        int IKGD_IndexUpdate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ikon.it/IKGD_IndexOptimize", ReplyAction="*")]
        bool IKGD_IndexOptimize();
        
        // CODEGEN: Generating message contract since element name IKGD_Indexer_GetAreasListResult from namespace http://www.ikon.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ikon.it/IKGD_Indexer_GetAreasList", ReplyAction="*")]
        IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetAreasListResponse IKGD_Indexer_GetAreasList(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetAreasListRequest request);
        
        // CODEGEN: Generating message contract since element name IKGD_Indexer_GetResourceTypeListResult from namespace http://www.ikon.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ikon.it/IKGD_Indexer_GetResourceTypeList", ReplyAction="*")]
        IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetResourceTypeListResponse IKGD_Indexer_GetResourceTypeList(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetResourceTypeListRequest request);
        
        // CODEGEN: Generating message contract since element name strSearch from namespace http://www.ikon.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ikon.it/IKGD_Indexer_GetSearchResults", ReplyAction="*")]
        IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsResponse IKGD_Indexer_GetSearchResults(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRequest request);
        
        // CODEGEN: Generating message contract since element name strSearch from namespace http://www.ikon.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ikon.it/IKGD_Indexer_GetSearchResultsRaw01", ReplyAction="*")]
        IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw01Response IKGD_Indexer_GetSearchResultsRaw01(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw01Request request);
        
        // CODEGEN: Generating message contract since element name strSearch from namespace http://www.ikon.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ikon.it/IKGD_Indexer_GetSearchResultsRaw02", ReplyAction="*")]
        IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw02Response IKGD_Indexer_GetSearchResultsRaw02(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw02Request request);
        
        // CODEGEN: Generating message contract since element name IKGD_Indexer_RebuildRaw01Result from namespace http://www.ikon.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ikon.it/IKGD_Indexer_RebuildRaw01", ReplyAction="*")]
        IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_RebuildRaw01Response IKGD_Indexer_RebuildRaw01(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_RebuildRaw01Request request);
        
        // CODEGEN: Generating message contract since element name command from namespace http://www.ikon.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ikon.it/IKGD_Indexer_VFS01", ReplyAction="*")]
        IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_VFS01Response IKGD_Indexer_VFS01(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_VFS01Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IKGD_IndexRebuildRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IKGD_IndexRebuild", Namespace="http://www.ikon.it/", Order=0)]
        public IKGD_ResourceType_Library.IKGD_Indexer.IKGD_IndexRebuildRequestBody Body;
        
        public IKGD_IndexRebuildRequest() {
        }
        
        public IKGD_IndexRebuildRequest(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_IndexRebuildRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class IKGD_IndexRebuildRequestBody {
        
        public IKGD_IndexRebuildRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IKGD_IndexRebuildResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IKGD_IndexRebuildResponse", Namespace="http://www.ikon.it/", Order=0)]
        public IKGD_ResourceType_Library.IKGD_Indexer.IKGD_IndexRebuildResponseBody Body;
        
        public IKGD_IndexRebuildResponse() {
        }
        
        public IKGD_IndexRebuildResponse(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_IndexRebuildResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ikon.it/")]
    public partial class IKGD_IndexRebuildResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IKGD_IndexRebuildResult;
        
        public IKGD_IndexRebuildResponseBody() {
        }
        
        public IKGD_IndexRebuildResponseBody(string IKGD_IndexRebuildResult) {
            this.IKGD_IndexRebuildResult = IKGD_IndexRebuildResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IKGD_Indexer_GetAreasListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IKGD_Indexer_GetAreasList", Namespace="http://www.ikon.it/", Order=0)]
        public IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetAreasListRequestBody Body;
        
        public IKGD_Indexer_GetAreasListRequest() {
        }
        
        public IKGD_Indexer_GetAreasListRequest(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetAreasListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ikon.it/")]
    public partial class IKGD_Indexer_GetAreasListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool searchPreview;
        
        public IKGD_Indexer_GetAreasListRequestBody() {
        }
        
        public IKGD_Indexer_GetAreasListRequestBody(bool searchPreview) {
            this.searchPreview = searchPreview;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IKGD_Indexer_GetAreasListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IKGD_Indexer_GetAreasListResponse", Namespace="http://www.ikon.it/", Order=0)]
        public IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetAreasListResponseBody Body;
        
        public IKGD_Indexer_GetAreasListResponse() {
        }
        
        public IKGD_Indexer_GetAreasListResponse(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetAreasListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ikon.it/")]
    public partial class IKGD_Indexer_GetAreasListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement IKGD_Indexer_GetAreasListResult;
        
        public IKGD_Indexer_GetAreasListResponseBody() {
        }
        
        public IKGD_Indexer_GetAreasListResponseBody(System.Xml.XmlElement IKGD_Indexer_GetAreasListResult) {
            this.IKGD_Indexer_GetAreasListResult = IKGD_Indexer_GetAreasListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IKGD_Indexer_GetResourceTypeListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IKGD_Indexer_GetResourceTypeList", Namespace="http://www.ikon.it/", Order=0)]
        public IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetResourceTypeListRequestBody Body;
        
        public IKGD_Indexer_GetResourceTypeListRequest() {
        }
        
        public IKGD_Indexer_GetResourceTypeListRequest(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetResourceTypeListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class IKGD_Indexer_GetResourceTypeListRequestBody {
        
        public IKGD_Indexer_GetResourceTypeListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IKGD_Indexer_GetResourceTypeListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IKGD_Indexer_GetResourceTypeListResponse", Namespace="http://www.ikon.it/", Order=0)]
        public IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetResourceTypeListResponseBody Body;
        
        public IKGD_Indexer_GetResourceTypeListResponse() {
        }
        
        public IKGD_Indexer_GetResourceTypeListResponse(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetResourceTypeListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ikon.it/")]
    public partial class IKGD_Indexer_GetResourceTypeListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement IKGD_Indexer_GetResourceTypeListResult;
        
        public IKGD_Indexer_GetResourceTypeListResponseBody() {
        }
        
        public IKGD_Indexer_GetResourceTypeListResponseBody(System.Xml.XmlElement IKGD_Indexer_GetResourceTypeListResult) {
            this.IKGD_Indexer_GetResourceTypeListResult = IKGD_Indexer_GetResourceTypeListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IKGD_Indexer_GetSearchResultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IKGD_Indexer_GetSearchResults", Namespace="http://www.ikon.it/", Order=0)]
        public IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRequestBody Body;
        
        public IKGD_Indexer_GetSearchResultsRequest() {
        }
        
        public IKGD_Indexer_GetSearchResultsRequest(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ikon.it/")]
    public partial class IKGD_Indexer_GetSearchResultsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSearch;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public IKGD_ResourceType_Library.IKGD_Indexer.ArrayOfString allowedAreas;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string manager_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> sNodeFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<System.DateTime> dateStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> dateEnd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool searchPreview;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool formatMatches;
        
        public IKGD_Indexer_GetSearchResultsRequestBody() {
        }
        
        public IKGD_Indexer_GetSearchResultsRequestBody(string strSearch, IKGD_ResourceType_Library.IKGD_Indexer.ArrayOfString allowedAreas, string manager_type, System.Nullable<int> sNodeFolder, System.Nullable<System.DateTime> dateStart, System.Nullable<System.DateTime> dateEnd, bool searchPreview, bool formatMatches) {
            this.strSearch = strSearch;
            this.allowedAreas = allowedAreas;
            this.manager_type = manager_type;
            this.sNodeFolder = sNodeFolder;
            this.dateStart = dateStart;
            this.dateEnd = dateEnd;
            this.searchPreview = searchPreview;
            this.formatMatches = formatMatches;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IKGD_Indexer_GetSearchResultsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IKGD_Indexer_GetSearchResultsResponse", Namespace="http://www.ikon.it/", Order=0)]
        public IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsResponseBody Body;
        
        public IKGD_Indexer_GetSearchResultsResponse() {
        }
        
        public IKGD_Indexer_GetSearchResultsResponse(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ikon.it/")]
    public partial class IKGD_Indexer_GetSearchResultsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<IKGD_ResourceType_Library.IKGD_Indexer.IKGD_LuceneHit> IKGD_Indexer_GetSearchResultsResult;
        
        public IKGD_Indexer_GetSearchResultsResponseBody() {
        }
        
        public IKGD_Indexer_GetSearchResultsResponseBody(System.Collections.Generic.List<IKGD_ResourceType_Library.IKGD_Indexer.IKGD_LuceneHit> IKGD_Indexer_GetSearchResultsResult) {
            this.IKGD_Indexer_GetSearchResultsResult = IKGD_Indexer_GetSearchResultsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IKGD_Indexer_GetSearchResultsRaw01Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IKGD_Indexer_GetSearchResultsRaw01", Namespace="http://www.ikon.it/", Order=0)]
        public IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw01RequestBody Body;
        
        public IKGD_Indexer_GetSearchResultsRaw01Request() {
        }
        
        public IKGD_Indexer_GetSearchResultsRaw01Request(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw01RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ikon.it/")]
    public partial class IKGD_Indexer_GetSearchResultsRaw01RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSearch;
        
        public IKGD_Indexer_GetSearchResultsRaw01RequestBody() {
        }
        
        public IKGD_Indexer_GetSearchResultsRaw01RequestBody(string strSearch) {
            this.strSearch = strSearch;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IKGD_Indexer_GetSearchResultsRaw01Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IKGD_Indexer_GetSearchResultsRaw01Response", Namespace="http://www.ikon.it/", Order=0)]
        public IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw01ResponseBody Body;
        
        public IKGD_Indexer_GetSearchResultsRaw01Response() {
        }
        
        public IKGD_Indexer_GetSearchResultsRaw01Response(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw01ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ikon.it/")]
    public partial class IKGD_Indexer_GetSearchResultsRaw01ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<IKGD_ResourceType_Library.IKGD_Indexer.IKGD_LuceneHit> IKGD_Indexer_GetSearchResultsRaw01Result;
        
        public IKGD_Indexer_GetSearchResultsRaw01ResponseBody() {
        }
        
        public IKGD_Indexer_GetSearchResultsRaw01ResponseBody(System.Collections.Generic.List<IKGD_ResourceType_Library.IKGD_Indexer.IKGD_LuceneHit> IKGD_Indexer_GetSearchResultsRaw01Result) {
            this.IKGD_Indexer_GetSearchResultsRaw01Result = IKGD_Indexer_GetSearchResultsRaw01Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IKGD_Indexer_GetSearchResultsRaw02Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IKGD_Indexer_GetSearchResultsRaw02", Namespace="http://www.ikon.it/", Order=0)]
        public IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw02RequestBody Body;
        
        public IKGD_Indexer_GetSearchResultsRaw02Request() {
        }
        
        public IKGD_Indexer_GetSearchResultsRaw02Request(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw02RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ikon.it/")]
    public partial class IKGD_Indexer_GetSearchResultsRaw02RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSearch;
        
        public IKGD_Indexer_GetSearchResultsRaw02RequestBody() {
        }
        
        public IKGD_Indexer_GetSearchResultsRaw02RequestBody(string strSearch) {
            this.strSearch = strSearch;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IKGD_Indexer_GetSearchResultsRaw02Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IKGD_Indexer_GetSearchResultsRaw02Response", Namespace="http://www.ikon.it/", Order=0)]
        public IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw02ResponseBody Body;
        
        public IKGD_Indexer_GetSearchResultsRaw02Response() {
        }
        
        public IKGD_Indexer_GetSearchResultsRaw02Response(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw02ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ikon.it/")]
    public partial class IKGD_Indexer_GetSearchResultsRaw02ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<IKGD_ResourceType_Library.IKGD_Indexer.IKGD_LuceneHit> IKGD_Indexer_GetSearchResultsRaw02Result;
        
        public IKGD_Indexer_GetSearchResultsRaw02ResponseBody() {
        }
        
        public IKGD_Indexer_GetSearchResultsRaw02ResponseBody(System.Collections.Generic.List<IKGD_ResourceType_Library.IKGD_Indexer.IKGD_LuceneHit> IKGD_Indexer_GetSearchResultsRaw02Result) {
            this.IKGD_Indexer_GetSearchResultsRaw02Result = IKGD_Indexer_GetSearchResultsRaw02Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IKGD_Indexer_RebuildRaw01Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IKGD_Indexer_RebuildRaw01", Namespace="http://www.ikon.it/", Order=0)]
        public IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_RebuildRaw01RequestBody Body;
        
        public IKGD_Indexer_RebuildRaw01Request() {
        }
        
        public IKGD_Indexer_RebuildRaw01Request(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_RebuildRaw01RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ikon.it/")]
    public partial class IKGD_Indexer_RebuildRaw01RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int maxRecords;
        
        public IKGD_Indexer_RebuildRaw01RequestBody() {
        }
        
        public IKGD_Indexer_RebuildRaw01RequestBody(int maxRecords) {
            this.maxRecords = maxRecords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IKGD_Indexer_RebuildRaw01Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IKGD_Indexer_RebuildRaw01Response", Namespace="http://www.ikon.it/", Order=0)]
        public IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_RebuildRaw01ResponseBody Body;
        
        public IKGD_Indexer_RebuildRaw01Response() {
        }
        
        public IKGD_Indexer_RebuildRaw01Response(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_RebuildRaw01ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ikon.it/")]
    public partial class IKGD_Indexer_RebuildRaw01ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement IKGD_Indexer_RebuildRaw01Result;
        
        public IKGD_Indexer_RebuildRaw01ResponseBody() {
        }
        
        public IKGD_Indexer_RebuildRaw01ResponseBody(System.Xml.XmlElement IKGD_Indexer_RebuildRaw01Result) {
            this.IKGD_Indexer_RebuildRaw01Result = IKGD_Indexer_RebuildRaw01Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IKGD_Indexer_VFS01Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IKGD_Indexer_VFS01", Namespace="http://www.ikon.it/", Order=0)]
        public IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_VFS01RequestBody Body;
        
        public IKGD_Indexer_VFS01Request() {
        }
        
        public IKGD_Indexer_VFS01Request(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_VFS01RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ikon.it/")]
    public partial class IKGD_Indexer_VFS01RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string command;
        
        public IKGD_Indexer_VFS01RequestBody() {
        }
        
        public IKGD_Indexer_VFS01RequestBody(string command) {
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IKGD_Indexer_VFS01Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IKGD_Indexer_VFS01Response", Namespace="http://www.ikon.it/", Order=0)]
        public IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_VFS01ResponseBody Body;
        
        public IKGD_Indexer_VFS01Response() {
        }
        
        public IKGD_Indexer_VFS01Response(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_VFS01ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ikon.it/")]
    public partial class IKGD_Indexer_VFS01ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement IKGD_Indexer_VFS01Result;
        
        public IKGD_Indexer_VFS01ResponseBody() {
        }
        
        public IKGD_Indexer_VFS01ResponseBody(System.Xml.XmlElement IKGD_Indexer_VFS01Result) {
            this.IKGD_Indexer_VFS01Result = IKGD_Indexer_VFS01Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IndexerSoapChannel : IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class IndexerSoapClient : System.ServiceModel.ClientBase<IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap>, IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap {
        
        public IndexerSoapClient() {
        }
        
        public IndexerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IndexerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndexerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndexerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKGD_ResourceType_Library.IKGD_Indexer.IKGD_IndexRebuildResponse IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap.IKGD_IndexRebuild(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_IndexRebuildRequest request) {
            return base.Channel.IKGD_IndexRebuild(request);
        }
        
        public string IKGD_IndexRebuild() {
            IKGD_ResourceType_Library.IKGD_Indexer.IKGD_IndexRebuildRequest inValue = new IKGD_ResourceType_Library.IKGD_Indexer.IKGD_IndexRebuildRequest();
            inValue.Body = new IKGD_ResourceType_Library.IKGD_Indexer.IKGD_IndexRebuildRequestBody();
            IKGD_ResourceType_Library.IKGD_Indexer.IKGD_IndexRebuildResponse retVal = ((IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap)(this)).IKGD_IndexRebuild(inValue);
            return retVal.Body.IKGD_IndexRebuildResult;
        }
        
        public int IKGD_IndexUpdate() {
            return base.Channel.IKGD_IndexUpdate();
        }
        
        public bool IKGD_IndexOptimize() {
            return base.Channel.IKGD_IndexOptimize();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetAreasListResponse IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap.IKGD_Indexer_GetAreasList(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetAreasListRequest request) {
            return base.Channel.IKGD_Indexer_GetAreasList(request);
        }
        
        public System.Xml.XmlElement IKGD_Indexer_GetAreasList(bool searchPreview) {
            IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetAreasListRequest inValue = new IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetAreasListRequest();
            inValue.Body = new IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetAreasListRequestBody();
            inValue.Body.searchPreview = searchPreview;
            IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetAreasListResponse retVal = ((IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap)(this)).IKGD_Indexer_GetAreasList(inValue);
            return retVal.Body.IKGD_Indexer_GetAreasListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetResourceTypeListResponse IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap.IKGD_Indexer_GetResourceTypeList(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetResourceTypeListRequest request) {
            return base.Channel.IKGD_Indexer_GetResourceTypeList(request);
        }
        
        public System.Xml.XmlElement IKGD_Indexer_GetResourceTypeList() {
            IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetResourceTypeListRequest inValue = new IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetResourceTypeListRequest();
            inValue.Body = new IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetResourceTypeListRequestBody();
            IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetResourceTypeListResponse retVal = ((IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap)(this)).IKGD_Indexer_GetResourceTypeList(inValue);
            return retVal.Body.IKGD_Indexer_GetResourceTypeListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsResponse IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap.IKGD_Indexer_GetSearchResults(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRequest request) {
            return base.Channel.IKGD_Indexer_GetSearchResults(request);
        }
        
        public System.Collections.Generic.List<IKGD_ResourceType_Library.IKGD_Indexer.IKGD_LuceneHit> IKGD_Indexer_GetSearchResults(string strSearch, IKGD_ResourceType_Library.IKGD_Indexer.ArrayOfString allowedAreas, string manager_type, System.Nullable<int> sNodeFolder, System.Nullable<System.DateTime> dateStart, System.Nullable<System.DateTime> dateEnd, bool searchPreview, bool formatMatches) {
            IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRequest inValue = new IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRequest();
            inValue.Body = new IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRequestBody();
            inValue.Body.strSearch = strSearch;
            inValue.Body.allowedAreas = allowedAreas;
            inValue.Body.manager_type = manager_type;
            inValue.Body.sNodeFolder = sNodeFolder;
            inValue.Body.dateStart = dateStart;
            inValue.Body.dateEnd = dateEnd;
            inValue.Body.searchPreview = searchPreview;
            inValue.Body.formatMatches = formatMatches;
            IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsResponse retVal = ((IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap)(this)).IKGD_Indexer_GetSearchResults(inValue);
            return retVal.Body.IKGD_Indexer_GetSearchResultsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw01Response IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap.IKGD_Indexer_GetSearchResultsRaw01(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw01Request request) {
            return base.Channel.IKGD_Indexer_GetSearchResultsRaw01(request);
        }
        
        public System.Collections.Generic.List<IKGD_ResourceType_Library.IKGD_Indexer.IKGD_LuceneHit> IKGD_Indexer_GetSearchResultsRaw01(string strSearch) {
            IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw01Request inValue = new IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw01Request();
            inValue.Body = new IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw01RequestBody();
            inValue.Body.strSearch = strSearch;
            IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw01Response retVal = ((IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap)(this)).IKGD_Indexer_GetSearchResultsRaw01(inValue);
            return retVal.Body.IKGD_Indexer_GetSearchResultsRaw01Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw02Response IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap.IKGD_Indexer_GetSearchResultsRaw02(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw02Request request) {
            return base.Channel.IKGD_Indexer_GetSearchResultsRaw02(request);
        }
        
        public System.Collections.Generic.List<IKGD_ResourceType_Library.IKGD_Indexer.IKGD_LuceneHit> IKGD_Indexer_GetSearchResultsRaw02(string strSearch) {
            IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw02Request inValue = new IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw02Request();
            inValue.Body = new IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw02RequestBody();
            inValue.Body.strSearch = strSearch;
            IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_GetSearchResultsRaw02Response retVal = ((IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap)(this)).IKGD_Indexer_GetSearchResultsRaw02(inValue);
            return retVal.Body.IKGD_Indexer_GetSearchResultsRaw02Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_RebuildRaw01Response IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap.IKGD_Indexer_RebuildRaw01(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_RebuildRaw01Request request) {
            return base.Channel.IKGD_Indexer_RebuildRaw01(request);
        }
        
        public System.Xml.XmlElement IKGD_Indexer_RebuildRaw01(int maxRecords) {
            IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_RebuildRaw01Request inValue = new IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_RebuildRaw01Request();
            inValue.Body = new IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_RebuildRaw01RequestBody();
            inValue.Body.maxRecords = maxRecords;
            IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_RebuildRaw01Response retVal = ((IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap)(this)).IKGD_Indexer_RebuildRaw01(inValue);
            return retVal.Body.IKGD_Indexer_RebuildRaw01Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_VFS01Response IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap.IKGD_Indexer_VFS01(IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_VFS01Request request) {
            return base.Channel.IKGD_Indexer_VFS01(request);
        }
        
        public System.Xml.XmlElement IKGD_Indexer_VFS01(string command) {
            IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_VFS01Request inValue = new IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_VFS01Request();
            inValue.Body = new IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_VFS01RequestBody();
            inValue.Body.command = command;
            IKGD_ResourceType_Library.IKGD_Indexer.IKGD_Indexer_VFS01Response retVal = ((IKGD_ResourceType_Library.IKGD_Indexer.IndexerSoap)(this)).IKGD_Indexer_VFS01(inValue);
            return retVal.Body.IKGD_Indexer_VFS01Result;
        }
    }
}
