//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ikon.IKCMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesBase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesBase() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IKCMS_Resources.Resources.ResourcesBase", typeof(ResourcesBase).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indietro.
        /// </summary>
        public static string Back_Button {
            get {
                return ResourceManager.GetString("Back_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Breadcrumbs_Home {
            get {
                return ResourceManager.GetString("Breadcrumbs_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |&amp;nbsp;.
        /// </summary>
        public static string Breadcrumbs_Separator {
            get {
                return ResourceManager.GetString("Breadcrumbs_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerca.
        /// </summary>
        public static string CmsSearch_Button {
            get {
                return ResourceManager.GetString("CmsSearch_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vai ».
        /// </summary>
        public static string CmsSearch_GO {
            get {
                return ResourceManager.GetString("CmsSearch_GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ricerca non ha fornito nessun risultato.
        /// </summary>
        public static string CmsSearch_NoResults {
            get {
                return ResourceManager.GetString("CmsSearch_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risultati trovati.
        /// </summary>
        public static string CmsSearch_ResultsFound {
            get {
                return ResourceManager.GetString("CmsSearch_ResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testo cercato.
        /// </summary>
        public static string CmsSearch_SearchedText {
            get {
                return ResourceManager.GetString("CmsSearch_SearchedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cerca nel sito.
        /// </summary>
        public static string CmsSearch_Watermark {
            get {
                return ResourceManager.GetString("CmsSearch_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd MMMM yyyy.
        /// </summary>
        public static string Dates_FormatLong {
            get {
                return ResourceManager.GetString("Dates_FormatLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        public static string Dates_FormatShort {
            get {
                return ResourceManager.GetString("Dates_FormatShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Dates_RangeSeparator {
            get {
                return ResourceManager.GetString("Dates_RangeSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;copy; Ikon 2012.
        /// </summary>
        public static string Footer_Copyright {
            get {
                return ResourceManager.GetString("Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by: &lt;a href=&quot;http://www.ikon.it/&quot; &gt;Ikon S.r.l.&lt;/a&gt;.
        /// </summary>
        public static string Footer_PoweredBy {
            get {
                return ResourceManager.GetString("Footer_PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allegati.
        /// </summary>
        public static string Label_Allegati {
            get {
                return ResourceManager.GetString("Label_Allegati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Personale Utente.
        /// </summary>
        public static string Label_AreaUtente {
            get {
                return ResourceManager.GetString("Label_AreaUtente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to « Indietro.
        /// </summary>
        public static string Label_Back {
            get {
                return ResourceManager.GetString("Label_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contattaci.
        /// </summary>
        public static string Label_Contact {
            get {
                return ResourceManager.GetString("Label_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Label_Home {
            get {
                return ResourceManager.GetString("Label_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua.
        /// </summary>
        public static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Label_Links {
            get {
                return ResourceManager.GetString("Label_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condividi.
        /// </summary>
        public static string Label_Share {
            get {
                return ResourceManager.GetString("Label_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mappa del sito.
        /// </summary>
        public static string Label_SiteMap {
            get {
                return ResourceManager.GetString("Label_SiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa.
        /// </summary>
        public static string Label_Stampa {
            get {
                return ResourceManager.GetString("Label_Stampa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string Label_Terms {
            get {
                return ResourceManager.GetString("Label_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutti.
        /// </summary>
        public static string Label_Tutti {
            get {
                return ResourceManager.GetString("Label_Tutti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicca qui.
        /// </summary>
        public static string Login_Clicca {
            get {
                return ResourceManager.GetString("Login_Clicca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per modificare la password.
        /// </summary>
        public static string Login_Modifica {
            get {
                return ResourceManager.GetString("Login_Modifica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai dimenticato la password?.
        /// </summary>
        public static string Login_PasswordDimenticata {
            get {
                return ResourceManager.GetString("Login_PasswordDimenticata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non sei registrato?.
        /// </summary>
        public static string Login_Registrati {
            get {
                return ResourceManager.GetString("Login_Registrati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benvenuto nella schermata di Login.&lt;br&gt;
        ///Per poter accedere ai servizi è necessario effettuare l&apos;autenticazione.&lt;br&gt;
        ///Inserisci &lt;strong&gt;username&lt;/strong&gt; e &lt;strong&gt;password&lt;/strong&gt; e clicca sul pulsante di invio per accedere all&apos;area riservata..
        /// </summary>
        public static string Login_Text {
            get {
                return ResourceManager.GetString("Login_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome utente.
        /// </summary>
        public static string Login_UserName {
            get {
                return ResourceManager.GetString("Login_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benvenuto nella schermata di Login.&lt;br&gt;
        ///Per poter accedere ai servizi è necessario effettuare l&apos;autenticazione.&lt;br&gt;
        ///Inserisci &lt;strong&gt;username&lt;/strong&gt; e &lt;strong&gt;password&lt;/strong&gt; e clicca sul pulsante di invio per accedere all&apos;area riservata..
        /// </summary>
        public static string LoginBox_Text {
            get {
                return ResourceManager.GetString("LoginBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area personale.
        /// </summary>
        public static string LoginBox_Title {
            get {
                return ResourceManager.GetString("LoginBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ordina per.
        /// </summary>
        public static string Ordina {
            get {
                return ResourceManager.GetString("Ordina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nome.
        /// </summary>
        public static string Ordina_Nome {
            get {
                return ResourceManager.GetString("Ordina_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prezzo.
        /// </summary>
        public static string Ordina_Prezzo {
            get {
                return ResourceManager.GetString("Ordina_Prezzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to più recenti.
        /// </summary>
        public static string Ordina_Recenti {
            get {
                return ResourceManager.GetString("Ordina_Recenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seleziona vista:.
        /// </summary>
        public static string Ordina_VistaSelect {
            get {
                return ResourceManager.GetString("Ordina_VistaSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to più votati.
        /// </summary>
        public static string Ordina_Vota {
            get {
                return ResourceManager.GetString("Ordina_Vota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pagina.
        /// </summary>
        public static string Pager_Page {
            get {
                return ResourceManager.GetString("Pager_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatta &amp;raquo;.
        /// </summary>
        public static string Paragraph_Compact {
            get {
                return ResourceManager.GetString("Paragraph_Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leggi tutto &amp;raquo;.
        /// </summary>
        public static string Paragraph_Expand {
            get {
                return ResourceManager.GetString("Paragraph_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dal.
        /// </summary>
        public static string TagSearch_From {
            get {
                return ResourceManager.GetString("TagSearch_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci la parola chiave.
        /// </summary>
        public static string TagSearch_KeyWatermark {
            get {
                return ResourceManager.GetString("TagSearch_KeyWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo.
        /// </summary>
        public static string TagSearch_Range {
            get {
                return ResourceManager.GetString("TagSearch_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to al.
        /// </summary>
        public static string TagSearch_To {
            get {
                return ResourceManager.GetString("TagSearch_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikon Multimedia.
        /// </summary>
        public static string Title_Head {
            get {
                return ResourceManager.GetString("Title_Head", resourceCulture);
            }
        }
    }
}
