//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4223
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKGD_Auth_Modules.SSO_ServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSO_UserInfo", Namespace="http://sso.ikon.it/")]
    [System.SerializableAttribute()]
    public partial class SSO_UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<IKGD_Auth_Modules.SSO_ServiceClient.SSO_UserVariable> UserVariablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        private System.Guid UserIdField;
        
        private int IdLLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IKGD_Auth_Modules.SSO_ServiceClient.ArrayOfString RolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IKGD_Auth_Modules.SSO_ServiceClient.ArrayOfString AreasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<IKGD_Auth_Modules.SSO_ServiceClient.SSO_UserVariable> UserVariables {
            get {
                return this.UserVariablesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserVariablesField, value) != true)) {
                    this.UserVariablesField = value;
                    this.RaisePropertyChanged("UserVariables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int IdLL {
            get {
                return this.IdLLField;
            }
            set {
                if ((this.IdLLField.Equals(value) != true)) {
                    this.IdLLField = value;
                    this.RaisePropertyChanged("IdLL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public IKGD_Auth_Modules.SSO_ServiceClient.ArrayOfString Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesField, value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public IKGD_Auth_Modules.SSO_ServiceClient.ArrayOfString Areas {
            get {
                return this.AreasField;
            }
            set {
                if ((object.ReferenceEquals(this.AreasField, value) != true)) {
                    this.AreasField = value;
                    this.RaisePropertyChanged("Areas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSO_UserVariable", Namespace="http://sso.ikon.it/")]
    [System.SerializableAttribute()]
    public partial class SSO_UserVariable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubSystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        private int TypeField;
        
        private IKGD_Auth_Modules.SSO_ServiceClient.SSO_KEYVALUE_TypeEnum TypeEnumField;
        
        private System.Nullable<int> ValueIntField;
        
        private System.Nullable<double> ValueDoubleField;
        
        private System.Nullable<System.DateTime> ValueDateField;
        
        private System.Nullable<System.DateTime> ValueDateExtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubSystem {
            get {
                return this.SubSystemField;
            }
            set {
                if ((object.ReferenceEquals(this.SubSystemField, value) != true)) {
                    this.SubSystemField = value;
                    this.RaisePropertyChanged("SubSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string KeyParent {
            get {
                return this.KeyParentField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyParentField, value) != true)) {
                    this.KeyParentField = value;
                    this.RaisePropertyChanged("KeyParent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public IKGD_Auth_Modules.SSO_ServiceClient.SSO_KEYVALUE_TypeEnum TypeEnum {
            get {
                return this.TypeEnumField;
            }
            set {
                if ((this.TypeEnumField.Equals(value) != true)) {
                    this.TypeEnumField = value;
                    this.RaisePropertyChanged("TypeEnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> ValueInt {
            get {
                return this.ValueIntField;
            }
            set {
                if ((this.ValueIntField.Equals(value) != true)) {
                    this.ValueIntField = value;
                    this.RaisePropertyChanged("ValueInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<double> ValueDouble {
            get {
                return this.ValueDoubleField;
            }
            set {
                if ((this.ValueDoubleField.Equals(value) != true)) {
                    this.ValueDoubleField = value;
                    this.RaisePropertyChanged("ValueDouble");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<System.DateTime> ValueDate {
            get {
                return this.ValueDateField;
            }
            set {
                if ((this.ValueDateField.Equals(value) != true)) {
                    this.ValueDateField = value;
                    this.RaisePropertyChanged("ValueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<System.DateTime> ValueDateExt {
            get {
                return this.ValueDateExtField;
            }
            set {
                if ((this.ValueDateExtField.Equals(value) != true)) {
                    this.ValueDateExtField = value;
                    this.RaisePropertyChanged("ValueDateExt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ValueString {
            get {
                return this.ValueStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueStringField, value) != true)) {
                    this.ValueStringField = value;
                    this.RaisePropertyChanged("ValueString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://sso.ikon.it/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSO_KEYVALUE_TypeEnum", Namespace="http://sso.ikon.it/")]
    public enum SSO_KEYVALUE_TypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        String = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Integer = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Double = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateTime = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateTimeRange = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Boolean = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sso.ikon.it/", ConfigurationName="SSO_ServiceClient.SSO_ServiceSoap")]
    public interface SSO_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name token from namespace http://sso.ikon.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sso.ikon.it/VerifyToken", ReplyAction="*")]
        IKGD_Auth_Modules.SSO_ServiceClient.VerifyTokenResponse VerifyToken(IKGD_Auth_Modules.SSO_ServiceClient.VerifyTokenRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://sso.ikon.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sso.ikon.it/AuthenticateUser", ReplyAction="*")]
        IKGD_Auth_Modules.SSO_ServiceClient.AuthenticateUserResponse AuthenticateUser(IKGD_Auth_Modules.SSO_ServiceClient.AuthenticateUserRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://sso.ikon.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sso.ikon.it/GetUserName", ReplyAction="*")]
        IKGD_Auth_Modules.SSO_ServiceClient.GetUserNameResponse GetUserName(IKGD_Auth_Modules.SSO_ServiceClient.GetUserNameRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://sso.ikon.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sso.ikon.it/GetUserInfo", ReplyAction="*")]
        IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoResponse GetUserInfo(IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://sso.ikon.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sso.ikon.it/GetUserInfoExt", ReplyAction="*")]
        IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoExtResponse GetUserInfoExt(IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoExtRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://sso.ikon.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sso.ikon.it/GetUserRoles", ReplyAction="*")]
        IKGD_Auth_Modules.SSO_ServiceClient.GetUserRolesResponse GetUserRoles(IKGD_Auth_Modules.SSO_ServiceClient.GetUserRolesRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://sso.ikon.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sso.ikon.it/GetUserAreas", ReplyAction="*")]
        IKGD_Auth_Modules.SSO_ServiceClient.GetUserAreasResponse GetUserAreas(IKGD_Auth_Modules.SSO_ServiceClient.GetUserAreasRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://sso.ikon.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sso.ikon.it/GetUserVariables", ReplyAction="*")]
        IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesResponse GetUserVariables(IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://sso.ikon.it/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sso.ikon.it/GetUserVariablesPublic", ReplyAction="*")]
        IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesPublicResponse GetUserVariablesPublic(IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesPublicRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyToken", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.VerifyTokenRequestBody Body;
        
        public VerifyTokenRequest() {
        }
        
        public VerifyTokenRequest(IKGD_Auth_Modules.SSO_ServiceClient.VerifyTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class VerifyTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public VerifyTokenRequestBody() {
        }
        
        public VerifyTokenRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyTokenResponse", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.VerifyTokenResponseBody Body;
        
        public VerifyTokenResponse() {
        }
        
        public VerifyTokenResponse(IKGD_Auth_Modules.SSO_ServiceClient.VerifyTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class VerifyTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerifyTokenResult;
        
        public VerifyTokenResponseBody() {
        }
        
        public VerifyTokenResponseBody(bool VerifyTokenResult) {
            this.VerifyTokenResult = VerifyTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUser", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.AuthenticateUserRequestBody Body;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(IKGD_Auth_Modules.SSO_ServiceClient.AuthenticateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class AuthenticateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public AuthenticateUserRequestBody() {
        }
        
        public AuthenticateUserRequestBody(string UserName, string Password) {
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserResponse", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.AuthenticateUserResponseBody Body;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(IKGD_Auth_Modules.SSO_ServiceClient.AuthenticateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class AuthenticateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticateUserResult;
        
        public AuthenticateUserResponseBody() {
        }
        
        public AuthenticateUserResponseBody(string AuthenticateUserResult) {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserName", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.GetUserNameRequestBody Body;
        
        public GetUserNameRequest() {
        }
        
        public GetUserNameRequest(IKGD_Auth_Modules.SSO_ServiceClient.GetUserNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class GetUserNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetUserNameRequestBody() {
        }
        
        public GetUserNameRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserNameResponse", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.GetUserNameResponseBody Body;
        
        public GetUserNameResponse() {
        }
        
        public GetUserNameResponse(IKGD_Auth_Modules.SSO_ServiceClient.GetUserNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class GetUserNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserNameResult;
        
        public GetUserNameResponseBody() {
        }
        
        public GetUserNameResponseBody(string GetUserNameResult) {
            this.GetUserNameResult = GetUserNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfo", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoRequestBody Body;
        
        public GetUserInfoRequest() {
        }
        
        public GetUserInfoRequest(IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class GetUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetUserInfoRequestBody() {
        }
        
        public GetUserInfoRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfoResponse", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoResponseBody Body;
        
        public GetUserInfoResponse() {
        }
        
        public GetUserInfoResponse(IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class GetUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.SSO_UserInfo GetUserInfoResult;
        
        public GetUserInfoResponseBody() {
        }
        
        public GetUserInfoResponseBody(IKGD_Auth_Modules.SSO_ServiceClient.SSO_UserInfo GetUserInfoResult) {
            this.GetUserInfoResult = GetUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoExtRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfoExt", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoExtRequestBody Body;
        
        public GetUserInfoExtRequest() {
        }
        
        public GetUserInfoExtRequest(IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoExtRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class GetUserInfoExtRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<bool> getRoles;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<bool> getAreas;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<bool> getVariables;
        
        public GetUserInfoExtRequestBody() {
        }
        
        public GetUserInfoExtRequestBody(string token, System.Nullable<bool> getRoles, System.Nullable<bool> getAreas, System.Nullable<bool> getVariables) {
            this.token = token;
            this.getRoles = getRoles;
            this.getAreas = getAreas;
            this.getVariables = getVariables;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoExtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfoExtResponse", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoExtResponseBody Body;
        
        public GetUserInfoExtResponse() {
        }
        
        public GetUserInfoExtResponse(IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoExtResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class GetUserInfoExtResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.SSO_UserInfo GetUserInfoExtResult;
        
        public GetUserInfoExtResponseBody() {
        }
        
        public GetUserInfoExtResponseBody(IKGD_Auth_Modules.SSO_ServiceClient.SSO_UserInfo GetUserInfoExtResult) {
            this.GetUserInfoExtResult = GetUserInfoExtResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserRolesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserRoles", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.GetUserRolesRequestBody Body;
        
        public GetUserRolesRequest() {
        }
        
        public GetUserRolesRequest(IKGD_Auth_Modules.SSO_ServiceClient.GetUserRolesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class GetUserRolesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetUserRolesRequestBody() {
        }
        
        public GetUserRolesRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserRolesResponse", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.GetUserRolesResponseBody Body;
        
        public GetUserRolesResponse() {
        }
        
        public GetUserRolesResponse(IKGD_Auth_Modules.SSO_ServiceClient.GetUserRolesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class GetUserRolesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.ArrayOfString GetUserRolesResult;
        
        public GetUserRolesResponseBody() {
        }
        
        public GetUserRolesResponseBody(IKGD_Auth_Modules.SSO_ServiceClient.ArrayOfString GetUserRolesResult) {
            this.GetUserRolesResult = GetUserRolesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAreasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserAreas", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.GetUserAreasRequestBody Body;
        
        public GetUserAreasRequest() {
        }
        
        public GetUserAreasRequest(IKGD_Auth_Modules.SSO_ServiceClient.GetUserAreasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class GetUserAreasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetUserAreasRequestBody() {
        }
        
        public GetUserAreasRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAreasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserAreasResponse", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.GetUserAreasResponseBody Body;
        
        public GetUserAreasResponse() {
        }
        
        public GetUserAreasResponse(IKGD_Auth_Modules.SSO_ServiceClient.GetUserAreasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class GetUserAreasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.ArrayOfString GetUserAreasResult;
        
        public GetUserAreasResponseBody() {
        }
        
        public GetUserAreasResponseBody(IKGD_Auth_Modules.SSO_ServiceClient.ArrayOfString GetUserAreasResult) {
            this.GetUserAreasResult = GetUserAreasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserVariablesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserVariables", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesRequestBody Body;
        
        public GetUserVariablesRequest() {
        }
        
        public GetUserVariablesRequest(IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class GetUserVariablesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetUserVariablesRequestBody() {
        }
        
        public GetUserVariablesRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserVariablesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserVariablesResponse", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesResponseBody Body;
        
        public GetUserVariablesResponse() {
        }
        
        public GetUserVariablesResponse(IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class GetUserVariablesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<IKGD_Auth_Modules.SSO_ServiceClient.SSO_UserVariable> GetUserVariablesResult;
        
        public GetUserVariablesResponseBody() {
        }
        
        public GetUserVariablesResponseBody(System.Collections.Generic.List<IKGD_Auth_Modules.SSO_ServiceClient.SSO_UserVariable> GetUserVariablesResult) {
            this.GetUserVariablesResult = GetUserVariablesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserVariablesPublicRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserVariablesPublic", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesPublicRequestBody Body;
        
        public GetUserVariablesPublicRequest() {
        }
        
        public GetUserVariablesPublicRequest(IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesPublicRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class GetUserVariablesPublicRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetUserVariablesPublicRequestBody() {
        }
        
        public GetUserVariablesPublicRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserVariablesPublicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserVariablesPublicResponse", Namespace="http://sso.ikon.it/", Order=0)]
        public IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesPublicResponseBody Body;
        
        public GetUserVariablesPublicResponse() {
        }
        
        public GetUserVariablesPublicResponse(IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesPublicResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sso.ikon.it/")]
    public partial class GetUserVariablesPublicResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<IKGD_Auth_Modules.SSO_ServiceClient.SSO_UserVariable> GetUserVariablesPublicResult;
        
        public GetUserVariablesPublicResponseBody() {
        }
        
        public GetUserVariablesPublicResponseBody(System.Collections.Generic.List<IKGD_Auth_Modules.SSO_ServiceClient.SSO_UserVariable> GetUserVariablesPublicResult) {
            this.GetUserVariablesPublicResult = GetUserVariablesPublicResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SSO_ServiceSoapChannel : IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SSO_ServiceSoapClient : System.ServiceModel.ClientBase<IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap>, IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap {
        
        public SSO_ServiceSoapClient() {
        }
        
        public SSO_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SSO_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSO_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSO_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKGD_Auth_Modules.SSO_ServiceClient.VerifyTokenResponse IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap.VerifyToken(IKGD_Auth_Modules.SSO_ServiceClient.VerifyTokenRequest request) {
            return base.Channel.VerifyToken(request);
        }
        
        public bool VerifyToken(string token) {
            IKGD_Auth_Modules.SSO_ServiceClient.VerifyTokenRequest inValue = new IKGD_Auth_Modules.SSO_ServiceClient.VerifyTokenRequest();
            inValue.Body = new IKGD_Auth_Modules.SSO_ServiceClient.VerifyTokenRequestBody();
            inValue.Body.token = token;
            IKGD_Auth_Modules.SSO_ServiceClient.VerifyTokenResponse retVal = ((IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap)(this)).VerifyToken(inValue);
            return retVal.Body.VerifyTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKGD_Auth_Modules.SSO_ServiceClient.AuthenticateUserResponse IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap.AuthenticateUser(IKGD_Auth_Modules.SSO_ServiceClient.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public string AuthenticateUser(string UserName, string Password) {
            IKGD_Auth_Modules.SSO_ServiceClient.AuthenticateUserRequest inValue = new IKGD_Auth_Modules.SSO_ServiceClient.AuthenticateUserRequest();
            inValue.Body = new IKGD_Auth_Modules.SSO_ServiceClient.AuthenticateUserRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            IKGD_Auth_Modules.SSO_ServiceClient.AuthenticateUserResponse retVal = ((IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap)(this)).AuthenticateUser(inValue);
            return retVal.Body.AuthenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKGD_Auth_Modules.SSO_ServiceClient.GetUserNameResponse IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap.GetUserName(IKGD_Auth_Modules.SSO_ServiceClient.GetUserNameRequest request) {
            return base.Channel.GetUserName(request);
        }
        
        public string GetUserName(string token) {
            IKGD_Auth_Modules.SSO_ServiceClient.GetUserNameRequest inValue = new IKGD_Auth_Modules.SSO_ServiceClient.GetUserNameRequest();
            inValue.Body = new IKGD_Auth_Modules.SSO_ServiceClient.GetUserNameRequestBody();
            inValue.Body.token = token;
            IKGD_Auth_Modules.SSO_ServiceClient.GetUserNameResponse retVal = ((IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap)(this)).GetUserName(inValue);
            return retVal.Body.GetUserNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoResponse IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap.GetUserInfo(IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoRequest request) {
            return base.Channel.GetUserInfo(request);
        }
        
        public IKGD_Auth_Modules.SSO_ServiceClient.SSO_UserInfo GetUserInfo(string token) {
            IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoRequest inValue = new IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoRequest();
            inValue.Body = new IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoRequestBody();
            inValue.Body.token = token;
            IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoResponse retVal = ((IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap)(this)).GetUserInfo(inValue);
            return retVal.Body.GetUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoExtResponse IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap.GetUserInfoExt(IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoExtRequest request) {
            return base.Channel.GetUserInfoExt(request);
        }
        
        public IKGD_Auth_Modules.SSO_ServiceClient.SSO_UserInfo GetUserInfoExt(string token, System.Nullable<bool> getRoles, System.Nullable<bool> getAreas, System.Nullable<bool> getVariables) {
            IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoExtRequest inValue = new IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoExtRequest();
            inValue.Body = new IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoExtRequestBody();
            inValue.Body.token = token;
            inValue.Body.getRoles = getRoles;
            inValue.Body.getAreas = getAreas;
            inValue.Body.getVariables = getVariables;
            IKGD_Auth_Modules.SSO_ServiceClient.GetUserInfoExtResponse retVal = ((IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap)(this)).GetUserInfoExt(inValue);
            return retVal.Body.GetUserInfoExtResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKGD_Auth_Modules.SSO_ServiceClient.GetUserRolesResponse IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap.GetUserRoles(IKGD_Auth_Modules.SSO_ServiceClient.GetUserRolesRequest request) {
            return base.Channel.GetUserRoles(request);
        }
        
        public IKGD_Auth_Modules.SSO_ServiceClient.ArrayOfString GetUserRoles(string token) {
            IKGD_Auth_Modules.SSO_ServiceClient.GetUserRolesRequest inValue = new IKGD_Auth_Modules.SSO_ServiceClient.GetUserRolesRequest();
            inValue.Body = new IKGD_Auth_Modules.SSO_ServiceClient.GetUserRolesRequestBody();
            inValue.Body.token = token;
            IKGD_Auth_Modules.SSO_ServiceClient.GetUserRolesResponse retVal = ((IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap)(this)).GetUserRoles(inValue);
            return retVal.Body.GetUserRolesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKGD_Auth_Modules.SSO_ServiceClient.GetUserAreasResponse IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap.GetUserAreas(IKGD_Auth_Modules.SSO_ServiceClient.GetUserAreasRequest request) {
            return base.Channel.GetUserAreas(request);
        }
        
        public IKGD_Auth_Modules.SSO_ServiceClient.ArrayOfString GetUserAreas(string token) {
            IKGD_Auth_Modules.SSO_ServiceClient.GetUserAreasRequest inValue = new IKGD_Auth_Modules.SSO_ServiceClient.GetUserAreasRequest();
            inValue.Body = new IKGD_Auth_Modules.SSO_ServiceClient.GetUserAreasRequestBody();
            inValue.Body.token = token;
            IKGD_Auth_Modules.SSO_ServiceClient.GetUserAreasResponse retVal = ((IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap)(this)).GetUserAreas(inValue);
            return retVal.Body.GetUserAreasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesResponse IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap.GetUserVariables(IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesRequest request) {
            return base.Channel.GetUserVariables(request);
        }
        
        public System.Collections.Generic.List<IKGD_Auth_Modules.SSO_ServiceClient.SSO_UserVariable> GetUserVariables(string token) {
            IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesRequest inValue = new IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesRequest();
            inValue.Body = new IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesRequestBody();
            inValue.Body.token = token;
            IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesResponse retVal = ((IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap)(this)).GetUserVariables(inValue);
            return retVal.Body.GetUserVariablesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesPublicResponse IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap.GetUserVariablesPublic(IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesPublicRequest request) {
            return base.Channel.GetUserVariablesPublic(request);
        }
        
        public System.Collections.Generic.List<IKGD_Auth_Modules.SSO_ServiceClient.SSO_UserVariable> GetUserVariablesPublic(string token) {
            IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesPublicRequest inValue = new IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesPublicRequest();
            inValue.Body = new IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesPublicRequestBody();
            inValue.Body.token = token;
            IKGD_Auth_Modules.SSO_ServiceClient.GetUserVariablesPublicResponse retVal = ((IKGD_Auth_Modules.SSO_ServiceClient.SSO_ServiceSoap)(this)).GetUserVariablesPublic(inValue);
            return retVal.Body.GetUserVariablesPublicResult;
        }
    }
}
