//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ikon.IKCMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesCustom {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesCustom() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleSite_Web.Resources.ResourcesCustom", typeof(ResourcesCustom).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accetto.
        /// </summary>
        public static string Contatto_AccettoPrivacy {
            get {
                return ResourceManager.GetString("Contatto_AccettoPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAP.
        /// </summary>
        public static string Contatto_Cap {
            get {
                return ResourceManager.GetString("Contatto_Cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Città.
        /// </summary>
        public static string Contatto_Citta {
            get {
                return ResourceManager.GetString("Contatto_Citta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognome.
        /// </summary>
        public static string Contatto_Cognome {
            get {
                return ResourceManager.GetString("Contatto_Cognome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Contatto_Fax {
            get {
                return ResourceManager.GetString("Contatto_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirizzo.
        /// </summary>
        public static string Contatto_Indirizzo {
            get {
                return ResourceManager.GetString("Contatto_Indirizzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invia.
        /// </summary>
        public static string Contatto_InviaPrivacy {
            get {
                return ResourceManager.GetString("Contatto_InviaPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Contatto_Mail {
            get {
                return ResourceManager.GetString("Contatto_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazione.
        /// </summary>
        public static string Contatto_Nazione {
            get {
                return ResourceManager.GetString("Contatto_Nazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Contatto_Nome {
            get {
                return ResourceManager.GetString("Contatto_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero civico.
        /// </summary>
        public static string Contatto_Numero {
            get {
                return ResourceManager.GetString("Contatto_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Contatto_Provincia {
            get {
                return ResourceManager.GetString("Contatto_Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Contatto_Tel {
            get {
                return ResourceManager.GetString("Contatto_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testo.
        /// </summary>
        public static string Contatto_Testo {
            get {
                return ResourceManager.GetString("Contatto_Testo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informativa ai sensi dell&apos;art. 13 d.lgs 196/03 recante &quot;Codice in materia di trattamento dei dati personali&quot;.&lt;br /&gt;
        ///            Il trattamento &amp;egrave; effettuato con strumenti elettronici, gestito da incaricati all&apos;uopo individuati e con l&apos;adozione delle misure minime richieste dalla normativa.&lt;br /&gt;
        ///            L&apos;eventuale rifiuto comporta l&apos;impossibilit&amp;agrave; di ricevere informazioni e di accesso alle iniziative. Possono essere esercitati i diritti previsti dall&apos;art. 7 del Codice..
        /// </summary>
        public static string Contatto_TestoPrivacy {
            get {
                return ResourceManager.GetString("Contatto_TestoPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci il tuo commento.
        /// </summary>
        public static string Contatto_TitoloCommento {
            get {
                return ResourceManager.GetString("Contatto_TitoloCommento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci il tuo indirizzo di posta elettronica.
        /// </summary>
        public static string Contatto_TitoloMail {
            get {
                return ResourceManager.GetString("Contatto_TitoloMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consenso al trattamento dei dati personali.
        /// </summary>
        public static string Contatto_TitoloPrivacy {
            get {
                return ResourceManager.GetString("Contatto_TitoloPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci il numero di telefono.
        /// </summary>
        public static string Contatto_TitoloTel {
            get {
                return ResourceManager.GetString("Contatto_TitoloTel", resourceCulture);
            }
        }
    }
}
